import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const { name, phone, course } = await request.json();

    if (!name || !phone || !course) {
      return Response.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Validate env vars are configured
    const gmailUser = process.env.GMAIL_USER;
    const gmailPass = process.env.GMAIL_APP_PASSWORD;

    if (!gmailUser || gmailUser === "your-gmail@gmail.com") {
      console.error("GMAIL_USER is not configured in .env.local");
      return Response.json(
        { success: false, error: "Email service not configured. Please set GMAIL_USER in .env.local" },
        { status: 500 }
      );
    }
    if (!gmailPass || gmailPass.includes("xxxx")) {
      console.error("GMAIL_APP_PASSWORD is not configured in .env.local");
      return Response.json(
        { success: false, error: "Email service not configured. Please set GMAIL_APP_PASSWORD in .env.local" },
        { status: 500 }
      );
    }

    // Strip spaces from app password (Gmail app passwords are sometimes copy-pasted with spaces)
    const cleanPass = gmailPass.replace(/\s/g, "");

    // Create transporter using Gmail SMTP with App Password
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: gmailUser,
        pass: cleanPass,
      },
    });

    const submittedAt = new Date().toLocaleString("en-IN", {
      timeZone: "Asia/Kolkata",
      dateStyle: "full",
      timeStyle: "short",
    });

    const mailOptions = {
      from: `"SkilIntern Leads" <${gmailUser}>`,  
      to: "pavankanna1920@gmail.com",
      subject: `🎯 New Lead: ${name} – ${course}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8" />
          <style>
            body { font-family: Arial, sans-serif; background: #f1f5f9; margin: 0; padding: 20px; }
            .card { background: #ffffff; border-radius: 12px; padding: 32px; max-width: 520px; margin: 0 auto; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
            .header { background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%); border-radius: 8px; padding: 20px 24px; margin-bottom: 28px; }
            .header h1 { color: #fff; font-size: 20px; margin: 0 0 4px; }
            .header p  { color: #c7d2fe; font-size: 13px; margin: 0; }
            .label { font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 4px; }
            .value { font-size: 16px; font-weight: 600; color: #0f172a; margin-bottom: 20px; }
            .badge { display: inline-block; background: #eef2ff; color: #4f46e5; border-radius: 999px; padding: 4px 12px; font-size: 13px; font-weight: 700; }
            .footer { margin-top: 28px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center; }
          </style>
        </head>
        <body>
          <div class="card">
            <div class="header">
              <h1>🎯 New Course Enquiry</h1>
              <p>A prospect just submitted a lead via the SkilIntern website.</p>
            </div>

            <div class="label">Full Name</div>
            <div class="value">${name}</div>

            <div class="label">Phone Number</div>
            <div class="value">${phone}</div>

            <div class="label">Interested Course</div>
            <div class="value"><span class="badge">${course}</span></div>

            <div class="label">Submitted At</div>
            <div class="value" style="font-size:14px; color:#475569;">${submittedAt} (IST)</div>

            <div class="footer">
              This email was auto-generated by the SkilIntern lead capture form.<br/>
              Please follow up with the prospect within 24 hours.
            </div>
          </div>
        </body>
        </html>
      `,
    };

    await transporter.sendMail(mailOptions);

    return Response.json({ success: true });
  } catch (error: unknown) {
    const errMsg = error instanceof Error ? error.message : String(error);
    console.error("Email send error:", errMsg);
    return Response.json(
      { success: false, error: errMsg },
      { status: 500 }
    );
  }
}
